### ISSUE TITLE
Stealthburner Heat Sets

### ISSUE THREAD

**Issue by 24Tigger24** [Stealthchanger/Toolchanger#25]
The Stealthburner's heat sets are located on a radius (see left side in the picture), which makes it difficult to get them into the correct position when inserting them.

My suggestion: a flat surface (see right side in the picture) and the heat sets sit under the surface or on the surface with longer screws used
![Stealthburner](https://github.com/Stealthchanger/Toolchanger/assets/155834359/176a1f7d-b498-4e13-8c73-0ce3e4dea60b)

**Comment by TheSin-** [comment]
It has to be on that side due to the amount of pull force required by the CW2 assembly to get a good amount of stiffness.  We also wanted to use the same sized fasteners, which is why they are where they are,  might be able to make a silghtly larger opening to get to them.  But all our efforts are currently on v2 which does not have this issue as all anymore since the geometry on v2 has been completely redone.

**Comment by TheSin-** [comment]
actually after re reading I like this, if we do an other v1 maintenance release we will add this.  @BT123D
